language: go
sudo: false
go_import_path: trimmer.io/go-xmp

go:
  - 1.8
  - 1.9
  - 1.10
  - tip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet -composites=false .
  - go test -v -race ./...